name: Ghost-Mesh Production Build
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: System Hardening & Dependencies
        run: |
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt clean
          sudo apt update --fix-missing
          sudo apt install -y build-essential git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev lzma lzma-dev tk-dev zip unzip openjdk-17-jdk

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install cython==0.29.33 buildozer packaging tomli jinja2 MarkupSafe toml build appdirs colorama sh six

      - name: Build APK with Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GhostMesh-APK-Package
          path: bin/*.apk
